version: "3"
services:
  nginx:
    build:
      context: ./dockerfile/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${CONF_DIR}/nginx/conf.d:/etc/nginx/conf.d/:rw
      - ${CONF_DIR}/nginx/vhost:/etc/nginx/vhost:rw
      - ${CONF_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${LOG_DIR}/nginx:/var/log/nginx/:rw
    restart: always
    networks:
      - default

  php72:
    build:
      context: ./dockerfile/php
      args:
        PHP_VERSION: ${PHP72_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_EXTENSIONS: ${PHP72_EXTENSIONS}
        MORE_EXTENSION_INSTALLER: php72.sh
        SWOOLE_VERSION: ${PHP7_SWOOLE_VERSION}
        SUPERVIOSORD_INSTALL: ${SUPERVIOSORD_INSTALL}
    ports:
      - "${PHP72_SWOFT_HOST_PORT}:18306"
      - "${PHP72_HYPERF_HOST_PORT}:9501"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${CONF_DIR}/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ${CONF_DIR}/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${CONF_DIR}/supervisord/supervisord.d:/etc/supervisord.d:rw
      - ${CONF_DIR}/supervisord/supervisord.conf:/etc/supervisord.conf:rw
      - ${LOG_DIR}/php72:/var/log/php:rw
      - ${LOG_DIR}/supervisor/supervisord.log:/var/log/supervisord.log:rw
    restart: always
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  php56:
    build:
      context: ./dockerfile/php
      args:
        PHP_VERSION: ${PHP56_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_EXTENSIONS: ${PHP56_EXTENSIONS}
        MORE_EXTENSION_INSTALLER: php56.sh
        SWOOLE_VERSION: ${PHP5_SWOOLE_VERSION}
        SUPERVIOSORD_INSTALL: ${SUPERVIOSORD_INSTALL}
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${CONF_DIR}/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ${CONF_DIR}/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${CONF_DIR}/supervisord/supervisord.d:/etc/supervisord.d:rw
      - ${CONF_DIR}/supervisord/supervisord.conf:/etc/supervisord.conf:rw
      - ${LOG_DIR}/php56:/var/log/php:rw
      - ${LOG_DIR}/supervisor/supervisord.log:/var/log/supervisord.log:rw
    restart: always
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  mysql:
    build:
      context: ./dockerfile/mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${CONF_DIR}/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:rw
      - ${DATA_DIR}/mysql:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  mongodb:
    build:
      context: ./dockerfile/mongodb
      args:
        MONGODB_VERSION: ${MONGODB_VERSION}
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_INITDB_ROOT_PASSWORD}"
    volumes:
      - ${DATA_DIR}/mongo:/data/db:rw
      - ${DATA_DIR}/mongo/mongo_key:/mongo:rw
    ports:
      - "${MONGODB_HOST_PORT}:27017"
    command:
      --auth

  redis:
    build:
      context: ./dockerfile/redis
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${CONF_DIR}/redis/redis.conf:/etc/redis.conf:rw
      - ${DATA_DIR}/redis:/data
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - default

  rabbitmq:
    build:
      context: ./dockerfile/rabbitmq
      args:
        RABBITMQ_VERSION: ${RABBITMQ_VERSION}
    restart: always
    networks:
          - default
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER="${RABBITMQ_DEFAULT_USER}"
      - RABBITMQ_DEFAULT_PASS="${RABBITMQ_DEFAULT_PASS}"
    volumes:
      - ${LOG_DIR}/rabbitmq:/var/log/rabbitmq
      - ${DATA_DIR}/rabbitmq:/var/lib/rabbitmq:rw

  phpredisadmin:
    build:
      context: ./dockerfile/phpredisadmin
      args:
        REDISMYADMIN_VERSION: ${REDISMYADMIN_VERSION}
    ports:
      - "${REDISMYADMIN_HOST_PORT}:80"
    networks:
      - default
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379

networks:
  default:
