version: "3"
services:
  nginx:
    build:
      context: nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        CONF_PATH: ${CONF_PATH}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${CODE_PATH}:/var/www/html/:rw
      - ${CONF_PATH}/nginx/conf/conf.d:/etc/nginx/conf.d:rw
      - ${CONF_PATH}/nginx/conf/vhost:/etc/nginx/vhost:rw
      - ${CONF_PATH}/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${LOG_PATH}/nginx:/var/log/nginx/:rw
    stdin_open: true
    tty: true
    restart: always
    networks:
      - dcnmp

  php72:
    build:
      context: php
      args:
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_VERSION: ${PHP_VERSION}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        PHP_MORE_EXTENSION_INSTALLER: ${PHP_MORE_EXTENSION_INSTALLER}
        PHP_SWOOLE_VERSION: ${PHP_SWOOLE_VERSION}
        PHP_SUPERVISORD_INSTALL: ${PHP_SUPERVISORD_INSTALL}
        CONF_PATH: ${CONF_PATH}
    ports:
      - "${PHP_HOST_PORT_9000}:9000"
      - "${PHP_HOST_PORT_9501}:9501"
      - "${PHP_HOST_PORT_18306}:18306"
    volumes:
      - ${CODE_PATH}:/var/www/html/:rw
      - ${CONF_PATH}/php/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ${CONF_PATH}/php/conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${CONF_PATH}/php/conf/supervisord/supervisord.d:/etc/supervisord.d:rw
      - ${CONF_PATH}/php/conf/supervisord/supervisord.conf:/etc/supervisord.conf:rw
      - ${LOG_PATH}/${PHP_VERSION}:/var/log/php:rw
      - ${LOG_PATH}/supervisord:/var/log/supervisord:rw
    restart: always
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    networks:
      - dcnmp

  mysql:
    build:
      context: mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
        CONF_PATH: ${CONF_PATH}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${CONF_PATH}/mysql/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:rw
      - ${DATA_PATH}/mysql:/var/lib/mysql/:rw
      - ${LOG_PATH}/mysql:/var/log/mysql:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - dcnmp

  mongodb:
    build:
      context: mongodb
      args:
        MONGODB_VERSION: ${MONGODB_VERSION}
        CONF_PATH: ${CONF_PATH}
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_INITDB_ROOT_PASSWORD}"
    volumes:
      - ${DATA_PATH}/mongo:/data/db:rw
      - ${DATA_PATH}/mongo/mongo_key:/mongo:rw
    ports:
      - "${MONGODB_HOST_PORT}:27017"
    restart: always
    stdin_open: true
    tty: true
    networks:
      - dcnmp
    command:
      --auth

  redis:
    build:
      context: redis
      args:
        REDIS_VERSION: ${REDIS_VERSION}
        CONF_PATH: ${CONF_PATH}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${CONF_PATH}/redis/conf/redis.conf:/etc/redis.conf:rw
      - ${DATA_PATH}/redis:/data
    restart: always
    stdin_open: true
    tty: true
    entrypoint: ["redis-server", "/etc/redis.conf"]
    networks:
      - dcnmp

  rabbitmq:
    build:
      context: rabbitmq
      args:
        RABBITMQ_VERSION: ${RABBITMQ_VERSION}
        CONF_PATH: ${CONF_PATH}
    ports:
      - "${RABBITMQ_HOST_PORT_C}:5672"
      - "${RABBITMQ_HOST_PORT_S}:15672"
    environment:
      - RABBITMQ_DEFAULT_USER="${RABBITMQ_DEFAULT_USER}"
      - RABBITMQ_DEFAULT_PASS="${RABBITMQ_DEFAULT_PASS}"
    volumes:
      - ${LOG_PATH}/rabbitmq:/var/log/rabbitmq
      - ${DATA_PATH}/rabbitmq:/var/lib/rabbitmq:rw
    stdin_open: true
    tty: true
    restart: always
    networks:
      - dcnmp

  phpredisadmin:
    build:
      context: phpredisadmin
      args:
        REDISMYADMIN_VERSION: ${REDISMYADMIN_VERSION}
        CONF_PATH: ${CONF_PATH}
    ports:
      - "${REDISMYADMIN_HOST_PORT}:80"
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    networks:
      - dcnmp

networks:
  dcnmp:
